// ─────────────────────────────────────────────
// S&P 500 FULL LIST
// ─────────────────────────────────────────────
const SP500 = [
  ["MMM","3M"],["AOS","A.O. Smith"],["ABT","Abbott"],["ABBV","AbbVie"],["ACN","Accenture"],
  ["ADBE","Adobe"],["AMD","AMD"],["AES","AES Corp"],["AFL","Aflac"],["A","Agilent"],
  ["APD","Air Products"],["ABNB","Airbnb"],["AKAM","Akamai"],["ALB","Albemarle"],["ARE","Alexandria RE"],
  ["ALGN","Align Tech"],["ALLE","Allegion"],["LNT","Alliant Energy"],["ALL","Allstate"],["GOOGL","Alphabet A"],
  ["GOOG","Alphabet C"],["MO","Altria"],["AMZN","Amazon"],["AMCR","Amcor"],["AEE","Ameren"],
  ["AAL","American Airlines"],["AEP","American Electric"],["AXP","American Express"],["AIG","American Intl"],["AMT","American Tower"],
  ["AWK","American Water"],["AMP","Ameriprise"],["AME","AMETEK"],["AMGN","Amgen"],["APH","Amphenol"],
  ["ADI","Analog Devices"],["ANSS","ANSYS"],["AON","Aon"],["APA","APA Corp"],["AAPL","Apple"],
  ["AMAT","Applied Materials"],["APTV","Aptiv"],["ACGL","Arch Capital"],["ADM","Archer-Daniels"],["ANET","Arista Networks"],
  ["AJG","Arthur J. Gallagher"],["AIZ","Assurant"],["T","AT&T"],["ATO","Atmos Energy"],["ADSK","Autodesk"],
  ["ADP","ADP"],["AZO","AutoZone"],["AVB","AvalonBay"],["AVY","Avery Dennison"],["AXON","Axon Enterprise"],
  ["BKR","Baker Hughes"],["BALL","Ball Corp"],["BAC","Bank of America"],["BK","BNY Mellon"],["BBWI","Bath & Body Works"],
  ["BAX","Baxter Intl"],["BDX","Becton Dickinson"],["WRB","W.R. Berkley"],["BBY","Best Buy"],["BIO","Bio-Rad"],
  ["TECH","Bio-Techne"],["BIIB","Biogen"],["BLK","BlackRock"],["BX","Blackstone"],["BA","Boeing"],
  ["BSX","Boston Scientific"],["BMY","Bristol-Myers"],["AVGO","Broadcom"],["BR","Broadridge"],["BRO","Brown & Brown"],
  ["BF-B","Brown-Forman B"],["BLDR","Builders FirstSource"],["BG","Bunge"],["BXP","BXP Inc"],["CHRW","C.H. Robinson"],
  ["CDNS","Cadence Design"],["CZR","Caesars"],["CPT","Camden Property"],["CPB","Campbell Soup"],["COF","Capital One"],
  ["CAH","Cardinal Health"],["KMX","CarMax"],["CCL","Carnival"],["CARR","Carrier Global"],["CTLT","Catalent"],
  ["CAT","Caterpillar"],["CBOE","Cboe Global"],["CBRE","CBRE Group"],["CDW","CDW Corp"],["CE","Celanese"],
  ["COR","Cencora"],["CNC","Centene"],["CNX","CNX Resources"],["CDAY","Ceridian"],["CF","CF Industries"],
  ["CRL","Charles River"],["SCHW","Charles Schwab"],["CHTR","Charter Comm"],["CVX","Chevron"],["CMG","Chipotle"],
  ["CB","Chubb"],["CHD","Church & Dwight"],["CI","Cigna"],["CINF","Cincinnati Financial"],["CTAS","Cintas"],
  ["CSCO","Cisco"],["C","Citigroup"],["CFG","Citizens Financial"],["CLX","Clorox"],["CME","CME Group"],
  ["CMS","CMS Energy"],["KO","Coca-Cola"],["CTSH","Cognizant"],["CL","Colgate-Palmolive"],["CMCSA","Comcast"],
  ["CAG","Conagra"],["COP","ConocoPhillips"],["ED","Consolidated Edison"],["STZ","Constellation Brands"],["CEG","Constellation Energy"],
  ["COO","Cooper Companies"],["CPRT","Copart"],["GLW","Corning"],["CPAY","Corpay"],["CTVA","Corteva"],
  ["CSGP","CoStar Group"],["COST","Costco"],["CTRA","Coterra Energy"],["CRWD","CrowdStrike"],["CCI","Crown Castle"],
  ["CSX","CSX Corp"],["CMI","Cummins"],["CVS","CVS Health"],["DHR","Danaher"],["DRI","Darden Restaurants"],
  ["DVA","DaVita"],["DAY","Dayforce"],["DE","Deere & Co"],["DELL","Dell Tech"],["DAL","Delta Air Lines"],
  ["DVN","Devon Energy"],["DXCM","Dexcom"],["FANG","Diamondback Energy"],["DLR","Digital Realty"],["DFS","Discover Financial"],
  ["DG","Dollar General"],["DLTR","Dollar Tree"],["D","Dominion Energy"],["DPZ","Dominos"],["DOV","Dover Corp"],
  ["DHI","D.R. Horton"],["DTE","DTE Energy"],["DUK","Duke Energy"],["DD","DuPont"],["EMN","Eastman Chemical"],
  ["ETN","Eaton Corp"],["EBAY","eBay"],["ECL","Ecolab"],["EIX","Edison Intl"],["EW","Edwards Lifesciences"],
  ["EA","Electronic Arts"],["ELV","Elevance Health"],["LLY","Eli Lilly"],["EMR","Emerson Electric"],["ENPH","Enphase Energy"],
  ["ETR","Entergy"],["EOG","EOG Resources"],["EPAM","EPAM Systems"],["EQT","EQT Corp"],["EFX","Equifax"],
  ["EQIX","Equinix"],["EQR","Equity Residential"],["ESS","Essex Property"],["EL","Estee Lauder"],["ETSY","Etsy"],
  ["EG","Everest Group"],["EVRG","Evergy"],["ES","Eversource"],["EXC","Exelon"],["EXPE","Expedia"],
  ["EXPD","Expeditors"],["EXR","Extra Space"],["XOM","ExxonMobil"],["FFIV","F5 Inc"],["FDS","FactSet"],
  ["FICO","Fair Isaac"],["FAST","Fastenal"],["FRT","Federal Realty"],["FDX","FedEx"],["FIS","Fidelity NatInfo"],
  ["FITB","Fifth Third"],["FSLR","First Solar"],["FE","FirstEnergy"],["FI","Fiserv"],["FMC","FMC Corp"],
  ["F","Ford Motor"],["FTNT","Fortinet"],["FTV","Fortive"],["FOXA","Fox Corp A"],["FOX","Fox Corp B"],
  ["BEN","Franklin Resources"],["FCX","Freeport-McMoRan"],["GRMN","Garmin"],["IT","Gartner"],["GE","GE Aerospace"],
  ["GEHC","GE HealthCare"],["GEV","GE Vernova"],["GEN","Gen Digital"],["GNRC","Generac"],["GD","General Dynamics"],
  ["GIS","General Mills"],["GM","General Motors"],["GPC","Genuine Parts"],["GILD","Gilead Sciences"],["GS","Goldman Sachs"],
  ["HAL","Halliburton"],["HIG","Hartford Financial"],["HAS","Hasbro"],["HCA","HCA Healthcare"],["DOC","Healthpeak"],
  ["HSIC","Henry Schein"],["HSY","Hershey"],["HES","Hess Corp"],["HPE","HP Enterprise"],["HLT","Hilton"],
  ["HOLX","Hologic"],["HD","Home Depot"],["HON","Honeywell"],["HRL","Hormel Foods"],["HST","Host Hotels"],
  ["HWM","Howmet Aerospace"],["HPQ","HP Inc"],["HUBB","Hubbell"],["HUM","Humana"],["HBAN","Huntington Bancshares"],
  ["HII","Huntington Ingalls"],["IBM","IBM"],["IEX","IDEX Corp"],["IDXX","IDEXX Labs"],["ITW","Illinois Tool"],
  ["INCY","Incyte"],["IR","Ingersoll Rand"],["PODD","Insulet"],["INTC","Intel"],["ICE","Intercontinental Exchange"],
  ["IFF","Intl Flavors"],["IP","International Paper"],["IPG","Interpublic"],["INTU","Intuit"],["ISRG","Intuitive Surgical"],
  ["IVZ","Invesco"],["INVH","Invitation Homes"],["IQV","IQVIA"],["IRM","Iron Mountain"],["JBHT","J.B. Hunt"],
  ["JBL","Jabil"],["JKHY","Jack Henry"],["J","Jacobs Solutions"],["JNJ","Johnson & Johnson"],["JCI","Johnson Controls"],
  ["JPM","JPMorgan Chase"],["JNPR","Juniper Networks"],["K","Kellanova"],["KVUE","Kenvue"],["KDP","Keurig Dr Pepper"],
  ["KEY","KeyCorp"],["KEYS","Keysight"],["KMB","Kimberly-Clark"],["KIM","Kimco Realty"],["KMI","Kinder Morgan"],
  ["KLAC","KLA Corp"],["KHC","Kraft Heinz"],["KR","Kroger"],["LHX","L3Harris"],["LH","Labcorp"],
  ["LRCX","Lam Research"],["LW","Lamb Weston"],["LVS","Las Vegas Sands"],["LDOS","Leidos"],["LEN","Lennar"],
  ["LII","Lennox"],["LYV","Live Nation"],["LKQ","LKQ Corp"],["LMT","Lockheed Martin"],["L","Loews"],
  ["LOW","Lowes"],["LULU","lululemon"],["LYB","LyondellBasell"],["MTB","M&T Bank"],["MRO","Marathon Oil"],
  ["MPC","Marathon Petroleum"],["MKTX","MarketAxess"],["MAR","Marriott"],["MMC","Marsh McLennan"],["MLM","Martin Marietta"],
  ["MAS","Masco"],["MA","Mastercard"],["MTCH","Match Group"],["MKC","McCormick"],["MCD","McDonalds"],
  ["MCK","McKesson"],["MDT","Medtronic"],["MRK","Merck"],["META","Meta Platforms"],["MET","MetLife"],
  ["MTD","Mettler-Toledo"],["MGM","MGM Resorts"],["MCHP","Microchip Tech"],["MU","Micron Tech"],["MSFT","Microsoft"],
  ["MAA","Mid-America Apt"],["MRNA","Moderna"],["MHK","Mohawk Industries"],["MOH","Molina Healthcare"],["TAP","Molson Coors"],
  ["MDLZ","Mondelez"],["MPWR","Monolithic Power"],["MNST","Monster Beverage"],["MCO","Moodys"],["MS","Morgan Stanley"],
  ["MOS","Mosaic"],["MSI","Motorola Solutions"],["MSCI","MSCI Inc"],["NDAQ","Nasdaq"],["NTAP","NetApp"],
  ["NFLX","Netflix"],["NEM","Newmont"],["NWSA","News Corp A"],["NWS","News Corp B"],["NEE","NextEra Energy"],
  ["NKE","Nike"],["NI","NiSource"],["NDSN","Nordson"],["NSC","Norfolk Southern"],["NTRS","Northern Trust"],
  ["NOC","Northrop Grumman"],["NCLH","Norwegian Cruise"],["NRG","NRG Energy"],["NUE","Nucor"],["NVDA","NVIDIA"],
  ["NVR","NVR Inc"],["NXPI","NXP Semi"],["ORLY","OReilly Auto"],["OXY","Occidental"],["ODFL","Old Dominion"],
  ["OMC","Omnicom"],["ON","ON Semi"],["OKE","ONEOK"],["ORCL","Oracle"],["OTIS","Otis Worldwide"],
  ["PCAR","PACCAR"],["PKG","Packaging Corp"],["PLTR","Palantir"],["PANW","Palo Alto Networks"],["PARA","Paramount"],
  ["PH","Parker Hannifin"],["PAYX","Paychex"],["PAYC","Paycom"],["PYPL","PayPal"],["PNR","Pentair"],
  ["PEP","PepsiCo"],["PFE","Pfizer"],["PCG","PGE"],["PM","Philip Morris"],["PSX","Phillips 66"],
  ["PNW","Pinnacle West"],["PNC","PNC Financial"],["POOL","Pool Corp"],["PPG","PPG Industries"],["PPL","PPL Corp"],
  ["PFG","Principal Financial"],["PG","Procter & Gamble"],["PGR","Progressive"],["PLD","Prologis"],["PRU","Prudential"],
  ["PEG","PSEG"],["PTC","PTC Inc"],["PSA","Public Storage"],["PHM","PulteGroup"],["QRVO","Qorvo"],
  ["PWR","Quanta Services"],["QCOM","Qualcomm"],["DGX","Quest Diagnostics"],["RL","Ralph Lauren"],["RJF","Raymond James"],
  ["RTX","RTX Corp"],["O","Realty Income"],["REG","Regency Centers"],["REGN","Regeneron"],["RF","Regions Financial"],
  ["RSG","Republic Services"],["RMD","ResMed"],["RVTY","Revvity"],["ROK","Rockwell Auto"],["ROL","Rollins"],
  ["ROP","Roper Tech"],["ROST","Ross Stores"],["RCL","Royal Caribbean"],["SPGI","S&P Global"],["CRM","Salesforce"],
  ["SBAC","SBA Comm"],["SLB","SLB"],["STX","Seagate"],["SRE","Sempra"],["NOW","ServiceNow"],
  ["SHW","Sherwin-Williams"],["SPG","Simon Property"],["SWKS","Skyworks"],["SJM","J.M. Smucker"],["SNA","Snap-on"],
  ["SOLV","Solventum"],["SO","Southern Company"],["LUV","Southwest Air"],["SWK","Stanley Black & Decker"],["SBUX","Starbucks"],
  ["STT","State Street"],["STLD","Steel Dynamics"],["STE","STERIS"],["SYK","Stryker"],["SMCI","Super Micro"],
  ["SYF","Synchrony"],["SNPS","Synopsys"],["SYY","Sysco"],["TMUS","T-Mobile"],["TROW","T. Rowe Price"],
  ["TTWO","Take-Two"],["TPR","Tapestry"],["TRGP","Targa Resources"],["TGT","Target"],["TEL","TE Connectivity"],
  ["TDY","Teledyne"],["TFX","Teleflex"],["TER","Teradyne"],["TSLA","Tesla"],["TXN","Texas Instruments"],
  ["TXT","Textron"],["TMO","Thermo Fisher"],["TJX","TJX Companies"],["TSCO","Tractor Supply"],["TT","Trane Technologies"],
  ["TDG","TransDigm"],["TRV","Travelers"],["TRMB","Trimble"],["TFC","Truist Financial"],["TYL","Tyler Tech"],
  ["TSN","Tyson Foods"],["USB","U.S. Bancorp"],["UBER","Uber"],["UDR","UDR Inc"],["ULTA","Ulta Beauty"],
  ["UNP","Union Pacific"],["UAL","United Airlines"],["UPS","UPS"],["URI","United Rentals"],["UNH","UnitedHealth"],
  ["UHS","Universal Health"],["VLO","Valero Energy"],["VTR","Ventas"],["VRSN","VeriSign"],["VRSK","Verisk"],
  ["VZ","Verizon"],["VRTX","Vertex Pharma"],["VTRS","Viatris"],["VICI","VICI Properties"],["V","Visa"],
  ["VST","Vistra Corp"],["VFC","VF Corp"],["VNO","Vornado Realty"],["WRK","WestRock"],["WAB","Wabtec"],
  ["WBA","Walgreens"],["WMT","Walmart"],["DIS","Walt Disney"],["WBD","Warner Bros Discovery"],["WM","Waste Management"],
  ["WAT","Waters Corp"],["WEC","WEC Energy"],["WFC","Wells Fargo"],["WELL","Welltower"],["WST","West Pharma"],
  ["WDC","Western Digital"],["WHR","Whirlpool"],["WTW","Willis Towers Watson"],["WY","Weyerhaeuser"],["WYNN","Wynn Resorts"],
  ["XEL","Xcel Energy"],["XYL","Xylem"],["YUM","Yum Brands"],["ZBRA","Zebra Tech"],["ZBH","Zimmer Biomet"],["ZTS","Zoetis"]
];

const NQ100 = [
  ["NVDA","NVIDIA"],["AAPL","Apple"],["MSFT","Microsoft"],["AMZN","Amazon"],["GOOGL","Alphabet A"],
  ["GOOG","Alphabet C"],["META","Meta Platforms"],["TSLA","Tesla"],["AVGO","Broadcom"],["COST","Costco"],
  ["NFLX","Netflix"],["ASML","ASML"],["AMD","AMD"],["LIN","Linde"],["QCOM","Qualcomm"],
  ["INTU","Intuit"],["ISRG","Intuitive Surgical"],["AMAT","Applied Materials"],["TXN","Texas Instruments"],["BKNG","Booking Holdings"],
  ["ADP","ADP"],["HON","Honeywell"],["AMGN","Amgen"],["PDD","PDD Holdings"],["VRTX","Vertex Pharma"],
  ["ADI","Analog Devices"],["PANW","Palo Alto Networks"],["SBUX","Starbucks"],["LRCX","Lam Research"],["CSX","CSX Corp"],
  ["GILD","Gilead Sciences"],["MU","Micron Tech"],["REGN","Regeneron"],["SNPS","Synopsys"],["CDNS","Cadence Design"],
  ["KLAC","KLA Corp"],["MELI","MercadoLibre"],["CRWD","CrowdStrike"],["CTAS","Cintas"],["ORLY","OReilly Auto"],
  ["MAR","Marriott"],["NXPI","NXP Semi"],["CEG","Constellation Energy"],["ABNB","Airbnb"],["FTNT","Fortinet"],
  ["PCAR","PACCAR"],["MRVL","Marvell Tech"],["ROST","Ross Stores"],["WDAY","Workday"],["ADSK","Autodesk"],
  ["CHTR","Charter Comm"],["PAYX","Paychex"],["CPRT","Copart"],["MCHP","Microchip Tech"],["FAST","Fastenal"],
  ["VRSK","Verisk"],["DXCM","Dexcom"],["ODFL","Old Dominion"],["IDXX","IDEXX Labs"],["BIIB","Biogen"],
  ["ON","ON Semi"],["GEHC","GE HealthCare"],["TTWO","Take-Two"],["FANG","Diamondback Energy"],["CDW","CDW Corp"],
  ["GFS","GlobalFoundries"],["ANSS","ANSYS"],["TEAM","Atlassian"],["ARM","ARM Holdings"],["ILMN","Illumina"],
  ["DDOG","Datadog"],["ZS","Zscaler"],["CTSH","Cognizant"],["AEP","American Electric"],["EA","Electronic Arts"],
  ["KDP","Keurig Dr Pepper"],["MNST","Monster Beverage"],["XEL","Xcel Energy"],["LULU","lululemon"],["WBA","Walgreens"],
  ["EBAY","eBay"],["DLTR","Dollar Tree"],["CSGP","CoStar Group"],["ZM","Zoom Video"],["ENPH","Enphase Energy"],
  ["ALGN","Align Tech"],["PYPL","PayPal"],["CMCSA","Comcast"],["INTC","Intel"],["MDLZ","Mondelez"],
  ["MDB","MongoDB"],["WBD","Warner Bros"],["NDAQ","Nasdaq"],["RIVN","Rivian"],["SIRI","Sirius XM"],
  ["PDD","PDD Holdings"],["JD","JD.com"],["LCID","Lucid Group"],["MRVL","Marvell Tech"],["SMCI","Super Micro"],
  ["DASH","DoorDash"],["GEHC","GE HealthCare"],["GFS","GlobalFoundries"],["FSLR","First Solar"],["CEG","Constellation Energy"]
];

const UNIVERSES = {
  SP500: { label: 'S&P 500 (503)', color: '#ff9500', list: () => SP500 },
  SP100: { label: 'S&P 100',       color: '#ff9500', list: () => SP500.slice(0, 100) },
  SP50:  { label: 'S&P 50',        color: '#ff9500', list: () => SP500.slice(0, 50) },
  NQ100: { label: 'Nasdaq 100',    color: '#a855f7', list: () => NQ100 },
  NQ50:  { label: 'Nasdaq 50',     color: '#a855f7', list: () => NQ100.slice(0, 50) },
};
